# Generated by Django 4.0.6 on 2022-07-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_history',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
