# Generated by Django 3.2.14 on 2022-07-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20220718_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
