# Generated by Django 4.0.6 on 2022-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_user_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_history',
            field=models.JSONField(null=True),
        ),
    ]
