# Generated by Django 4.0.6 on 2022-08-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_alter_user_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_history',
            field=models.JSONField(null=True),
        ),
    ]
